import "./globals.css";
import QueryProvider from "@/components/QueryProvider";

export const metadata = {
  title: "Academic Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <QueryProvider> {children}</QueryProvider>
      </body>
    </html>
  );
}
